name: HelloJava

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]
  workflow_dispatch:

jobs:    
  SayHello:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checlout@v3
      
      - name: Say it
        run: echo helloworld
    
    
